version: '3.1'
services:
  odoo:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=myodoo_usr
      - PASSWORD=myodoo_pwd
    networks:
      - odoo_network
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myodoo_usr
      - POSTGRES_PASSWORD=myodoo_pwd
    networks:
      - odoo_network
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  odoo_network:
    name: odoo_network
    external: true