name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - tp2/**
  pull_request:
    branches: [ "main" ]
    paths:
      - tp2/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker build and push
      uses: cloudposse/github-action-docker-build-push@1.11.0
      with:
        workdir: './tp2/'
        file: 'Dockerfile' # optional, default is Dockerfile
        organization: 'jeandonaldroselin'
        repository: 'bootcamp-devops-1-docker-tp2'
        registry: 'registry.docker.com'
        login: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
